# Problem 2

In [1]:
import pandas as pd
import numpy as np


In [2]:
path='D:\\Downloads\\advertising.csv'
data=pd.read_csv(path)
data

lendf=len(data)
print(lendf)

200


In [3]:
print(data.columns)
data.drop(['Unnamed: 0'],axis=1)


Index(['Unnamed: 0', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')


TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [4]:
data['yinterc']=1
data=data[['yinterc','TV','Radio','Newspaper','Sales']]

In [5]:
y=data.loc[:,'Sales']
np.array(y)

array([22.1, 10.4,  9.3, 18.5, 12.9,  7.2, 11.8, 13.2,  4.8, 10.6,  8.6,
       17.4,  9.2,  9.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 12.5,
        5.6, 15.5,  9.7, 12. , 15. , 15.9, 18.9, 10.5, 21.4, 11.9,  9.6,
       17.4,  9.5, 12.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 12.9,
        8.5, 14.9, 10.6, 23.2, 14.8,  9.7, 11.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 15.7, 14. , 18. ,  9.3,
        9.5, 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 12.3, 11.3, 13.6, 21.7, 15.2, 12. , 16. ,
       12.9, 16.7, 11.2,  7.3, 19.4, 22.2, 11.5, 16.9, 11.7, 15.5, 25.4,
       17.2, 11.7, 23.8, 14.8, 14.7, 20.7, 19.2,  7.2,  8.7,  5.3, 19.8,
       13.4, 21.8, 14.1, 15.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 11.6, 15.2, 19.7, 10.6,  6.6,  8.8, 24.7,  9.7,  1.6, 12.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 11.4, 10.3, 13.2, 25.4, 10.9, 10.1, 16

In [6]:
X = data.loc[:,'yinterc':'Newspaper']
np.array(X)

array([[  1. , 230.1,  37.8,  69.2],
       [  1. ,  44.5,  39.3,  45.1],
       [  1. ,  17.2,  45.9,  69.3],
       [  1. , 151.5,  41.3,  58.5],
       [  1. , 180.8,  10.8,  58.4],
       [  1. ,   8.7,  48.9,  75. ],
       [  1. ,  57.5,  32.8,  23.5],
       [  1. , 120.2,  19.6,  11.6],
       [  1. ,   8.6,   2.1,   1. ],
       [  1. , 199.8,   2.6,  21.2],
       [  1. ,  66.1,   5.8,  24.2],
       [  1. , 214.7,  24. ,   4. ],
       [  1. ,  23.8,  35.1,  65.9],
       [  1. ,  97.5,   7.6,   7.2],
       [  1. , 204.1,  32.9,  46. ],
       [  1. , 195.4,  47.7,  52.9],
       [  1. ,  67.8,  36.6, 114. ],
       [  1. , 281.4,  39.6,  55.8],
       [  1. ,  69.2,  20.5,  18.3],
       [  1. , 147.3,  23.9,  19.1],
       [  1. , 218.4,  27.7,  53.4],
       [  1. , 237.4,   5.1,  23.5],
       [  1. ,  13.2,  15.9,  49.6],
       [  1. , 228.3,  16.9,  26.2],
       [  1. ,  62.3,  12.6,  18.3],
       [  1. , 262.9,   3.5,  19.5],
       [  1. , 142.9,  29.3,  12.6],
 

##  I will use

$$
\begin{gather*}
β^*=(X^TX)^{-1}(X^TY)
\end{gather*}
$$


In [7]:
import scipy.linalg as la

In [8]:
X_Transposed=np.transpose(X)
X_Transposed

0     1     2      3      4     5     6      7    8      9    \
yinterc      1.0   1.0   1.0    1.0    1.0   1.0   1.0    1.0  1.0    1.0   
TV         230.1  44.5  17.2  151.5  180.8   8.7  57.5  120.2  8.6  199.8   
Radio       37.8  39.3  45.9   41.3   10.8  48.9  32.8   19.6  2.1    2.6   
Newspaper   69.2  45.1  69.3   58.5   58.4  75.0  23.5   11.6  1.0   21.2   

           ...   190   191   192    193    194   195   196    197    198  \
yinterc    ...   1.0   1.0   1.0    1.0    1.0   1.0   1.0    1.0    1.0   
TV         ...  39.5  75.5  17.2  166.8  149.7  38.2  94.2  177.0  283.6   
Radio      ...  41.1  10.8   4.1   42.0   35.6   3.7   4.9    9.3   42.0   
Newspaper  ...   5.8   6.0  31.6    3.6    6.0  13.8   8.1    6.4   66.2   

             199  
yinterc      1.0  
TV         232.1  
Radio        8.6  
Newspaper    8.7  

[4 rows x 200 columns]

In [9]:
P1=np.dot(X_Transposed,X)
P1Inverse=np.linalg.inv(P1)
P2=np.dot(X_Transposed,y)

In [10]:
#This will be our coefficients With  TVR,Radio,Newspaper Respectively
Beta=np.dot(P1Inverse,P2)
Beta

array([ 2.93888937e+00,  4.57646455e-02,  1.88530017e-01, -1.03749304e-03])

### Comparison To Linear Regression

In [11]:
import statsmodels.api
from sklearn.linear_model import LinearRegression
import pandas


In [12]:
x=data.loc[:,'TV':'Newspaper']
Y=data.loc[:,'Sales']

In [13]:
regression=statsmodels.api.OLS(y,X)

model=regression.fit()

print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Thu, 13 Jan 2022   Prob (F-statistic):           1.58e-96
Time:                        00:18:45   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
yinterc        2.9389      0.312      9.422      0.0